### ISSUE TITLE
Generate static libraries for librunecoral

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/librunecoral#3]
We want to generate static libraries for `librunecoral` so they can easily be linked into Rust.

This involves:

- [ ] Switching the build over to CMake **or** creating a custom bazel rune to generate static libraries
- [ ] Updating the Rust build script accordingly

**Comment by saidinesh5** [comment]
Given Google's recent statements about no compatibility guarantees between libedgetpu vs. tflite - should we move librunecoral over to cmake (+ dlopen or converting libedgetpu to use cmakelists - will be a pain due to absl etc.. i think) or do we just write the custom bazel rule like: https://github.com/bazelbuild/bazel/issues/5200 and https://github.com/bazelbuild/bazel/issues/1920
